In [4]:
import torch
ids0 = torch.Tensor([[1,2,3], [21,22,23]])

In [6]:
print(ids0)
print(ids0.shape)

tensor([[ 1.,  2.,  3.],
        [21., 22., 23.]])
torch.Size([2, 3])


In [14]:
index = torch.Tensor([[0, 1], [0,2]])
index = index.long()
result = torch.index_select(ids0[1], 0, index[1])

In [15]:
print(result)

tensor([21., 23.])


In [24]:
a = torch.tensor([11, 12])
b = torch.tensor([21, 22])
c = torch.tensor([31, 32])

x = torch.cat((a.expand([1,2]), b.expand([1,2])), dim=0)
x = torch.cat((x, c.expand([1,2])), dim=0)

In [25]:
print(x.shape)

torch.Size([3, 2])


In [ ]:
print(x.transpose())

In [29]:
import torch
A = torch.rand(2,3,4)
print(A.shape)
print(A[0][0])
B = torch.Tensor([[0, 1], [0,2], [2, 2]])

torch.Size([2, 3, 4])
tensor([0.2689, 0.3610, 0.9743, 0.8527])


In [30]:
dummy = B.unsqueeze(0).expand(A.size(0), B.size(0), B.size(1))

out = torch.gather(A, 2, dummy.to(torch.int64))

In [33]:
print(out[0][1])

tensor([0.8189, 0.8842])


In [35]:
print(A[0][1])

tensor([0.8189, 0.1788, 0.8842, 0.8710])


In [58]:
import torch.nn.functional as F
v = torch.rand(1,1,2,3)
padded_v = F.pad(input=v, pad=[0, 1], mode='constant', value=0)
print(padded_v.shape)
print(v)
print(padded_v)

torch.Size([1, 1, 2, 4])
tensor([[[[0.1812, 0.2549, 0.7230],
          [0.0119, 0.5052, 0.1972]]]])
tensor([[[[0.1812, 0.2549, 0.7230, 0.0000],
          [0.0119, 0.5052, 0.1972, 0.0000]]]])


In [43]:
A = torch.rand(3,4)
print(A.shape)
B = torch.Tensor([[0, 1], [0,2], [2, 2]])
print(B.shape)
out = torch.gather(A, -1, B.to(torch.int64))

torch.Size([3, 4])
torch.Size([3, 2])


In [47]:
print(A[2])
print(out[2])

tensor([0.1618, 0.5508, 0.7262, 0.0419])
tensor([0.7262, 0.7262])


In [62]:
A = torch.rand(3,4)
print(A.shape)

torch.Size([3, 4])


In [63]:
print(A.view(1,1,A.shape[0], A.shape[1]))

tensor([[[[0.1214, 0.7385, 0.4573, 0.9691],
          [0.8167, 0.2544, 0.7291, 0.8528],
          [0.4809, 0.7693, 0.2339, 0.4044]]]])


In [61]:
print(A.shape[-1])

4


In [88]:
# Scatter 
A=torch.zeros(3,4,5,6)
B=torch.rand(3,4,5,2)
index = torch.tensor([[1, 2], [2, 3], [3,4], [3,1], [2,2]])
print(index.unsqueeze(0).unsqueeze(0).shape)
expand_index = index.unsqueeze(0).unsqueeze(0).expand(3,4,5,2)
print(expand_index.shape)

torch.Size([1, 1, 5, 2])
torch.Size([3, 4, 5, 2])


In [90]:
C = torch.scatter(A, -1, expand_index.to(torch.int64), B)

In [91]:
print(C)

tensor([[[[0.0000, 0.5060, 0.3104, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.6218, 0.6796, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0240, 0.8735, 0.0000],
          [0.0000, 0.7898, 0.0000, 0.6231, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.5812, 0.0000, 0.0000, 0.0000]],

         [[0.0000, 0.2797, 0.6146, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.7329, 0.9637, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.8104, 0.0948, 0.0000],
          [0.0000, 0.4308, 0.0000, 0.6453, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.2734, 0.0000, 0.0000, 0.0000]],

         [[0.0000, 0.1776, 0.0049, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.2946, 0.3955, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.5659, 0.8462, 0.0000],
          [0.0000, 0.4335, 0.0000, 0.6527, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.1535, 0.0000, 0.0000, 0.0000]],

         [[0.0000, 0.4080, 0.4012, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.6611,